language: php
sudo: false
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4snapshot
env:
- TESTSCRIPT='script/dir/run.php'
- TESTSCRIPT='script/dirname/run.php'
- TESTSCRIPT='script/directories/dir/run.php'
- TESTSCRIPT='script/directories/dirname/run.php'
script: ./run.sh 
